---
- name: Install nginx and deploy site from git
  hosts: web
  become: true

  vars:
    repo_url: "https://github.com/peterherczeg/configmgmt_hw.git"
    repo_dest: "/opt/site"
    web_root: "/usr/share/nginx/html"

  tasks:
    - name: Install git
      ansible.builtin.dnf:
        name: git
        state: present

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Enable and start nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started

    - name: Clone/update repository to /opt/site
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        update: yes
        force: yes
      notify: Reload nginx

    - name: Ensure web root exists
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: nginx
        group: nginx
        mode: "0755"

    - name: Clear web root contents
      ansible.builtin.command: "rm -rf {{ web_root }}/*"
      changed_when: true

    - name: Copy site to web root (excluding .git)
      ansible.builtin.copy:
        src: "{{ repo_dest }}/"
        dest: "{{ web_root }}/"
        remote_src: true
        owner: nginx
        group: nginx
        mode: "0755"
      notify: Reload nginx

    - name: Remove .git from web root if copied
      ansible.builtin.file:
        path: "{{ web_root }}/.git"
        state: absent

  handlers:
    - name: Reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
